Dmitriyluba desicions
js-tasks-ru/js-20230223_dmitriylyba pull request #3
Opened 2023-03-02 06:38 UTC by Voanarges

finished exercises of 2 module

2023-03-02 06:39 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      .sort((a, b) => a.localeCompare(b, 'ru-RU', { caseFirst: 'upper' }))
устраните дубликаты кода!

2023-03-02 12:31 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      .reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-03-02 12:31 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete newArr[key]
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2023-03-02 12:31 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let key in obj) {
`const key`

2023-03-02 12:32 UTC, dosandk requested changes
решения sortString и omit следует поправить

2023-03-03 04:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-03 04:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-03 04:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-05 10:54 UTC, dosandk approved these changes
good 👍
решения к-е мы разбираем не обязательно копировать, просто нужно учесть те моменты на к-е мы обращаем внимание при разборе

2023-03-05 10:54 UTC, merged

2023-03-06 12:58 UTC, Voanarges commented
а я специально их вставляю + сохраняя свой вариант. Чтобы можно было в дальнейшем для себя сравнивать/вспоминать